const TIME_SHIFT_IN_SECONDS = 15
const DEFAULT_START_TIME = 0
const UNIX_TIME_START = 0
const TIME_SEPARATOR = ':'
const HOUR_IS_NOT_EXISTS = '00'
const BASE_SLIDER_COLOUR = '#969696'

export {
  TIME_SHIFT_IN_SECONDS,
  DEFAULT_START_TIME,
  UNIX_TIME_START,
  TIME_SEPARATOR,
  HOUR_IS_NOT_EXISTS,
  BASE_SLIDER_COLOUR
}
