const TIME_SHIFT_IN_SECONDS = 15
const DEFAULT_START_TIME = 0
const TIME_SEPARATOR = ':'
const HOUR_IS_NOT_EXISTS = '00'
const BASE_SLIDER_COLOUR = '#969696'
const MILLISECONDS_IN_SECOND = 1000

export {
  TIME_SHIFT_IN_SECONDS,
  DEFAULT_START_TIME,
  TIME_SEPARATOR,
  HOUR_IS_NOT_EXISTS,
  BASE_SLIDER_COLOUR,
  MILLISECONDS_IN_SECOND
}
