const DEFAULT_EPISODES_OFFSET = 0
const DEFAULT_EPISODES_LIMIT = 5

const DEFAULT_EPISODES_PAGINATION = {
  offset: DEFAULT_EPISODES_OFFSET,
  limit: DEFAULT_EPISODES_LIMIT
}

export { DEFAULT_EPISODES_LIMIT, DEFAULT_EPISODES_PAGINATION }
