const TIME_SHIFT_IN_SECONDS = 15
const DEFAULT_EPISODE_TRACK =
  'https://www.chosic.com/wp-content/uploads/2021/07/The-Epic-Hero-Epic-Cinematic-Keys-of-Moon-Music.mp3'

const DEFAULT_EPISODE_IMAGE =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADMAAAAzCAYAAAA6oTAqAAAAEXRFWHRTb2Z0d2FyZQBwbmdjcnVzaEB1SfMAAABQSURBVGje7dSxCQBACARB+2/ab8BEeQNhFi6WSYzYLYudDQYGBgYGBgYGBgYGBgYGBgZmcvDqYGBgmhivGQYGBgYGBgYGBgYGBgYGBgbmQw+P/eMrC5UTVAAAAABJRU5ErkJggg=='

const DEFAULT_START_TIME = 0
const UNIX_TIME_START = 0
const TIME_SEPARATOR = ':'
const HOUR_IS_NOT_EXISTS = '00'

export {
  TIME_SHIFT_IN_SECONDS,
  DEFAULT_EPISODE_TRACK,
  DEFAULT_EPISODE_IMAGE,
  DEFAULT_START_TIME,
  UNIX_TIME_START,
  TIME_SEPARATOR,
  HOUR_IS_NOT_EXISTS
}
